In [1]:
import numpy as np

In [2]:
import psycopg2

In [4]:
stars = np.loadtxt('stars.csv', delimiter=',', usecols=(0,2))

In [6]:
stars[:, 1] > 1

array([False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False, False,
       False,  True, False,  True, False, False,  True, False,  True,
       False,  True, False, False,  True, False,  True, False,  True,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False])

In [9]:
stars[stars[:, 1] > 1.0,:]

array([[3.3429700e+06, 1.0640000e+00],
       [3.3518880e+06, 1.0570000e+00],
       [6.9222440e+06, 1.4510000e+00],
       [8.3956600e+06, 1.0290000e+00],
       [9.5796410e+06, 1.3320000e+00],
       [1.0666592e+07, 1.9910000e+00],
       [1.0797460e+07, 1.0400000e+00],
       [1.0854555e+07, 1.0460000e+00],
       [1.0875245e+07, 1.4110000e+00],
       [1.0984090e+07, 1.0730000e+00],
       [1.1138155e+07, 1.0250000e+00],
       [1.1304958e+07, 1.0460000e+00],
       [1.1403044e+07, 1.1030000e+00],
       [1.1493732e+07, 1.0910000e+00],
       [1.1904151e+07, 1.0560000e+00]])

In [10]:
def query(file_name):
    stars = np.loadtxt(file_name, delimiter=',', usecols=(0,2))
    return stars[stars[:, 1] > 1.0,:]

In [11]:
query('stars.csv')

array([[3.3429700e+06, 1.0640000e+00],
       [3.3518880e+06, 1.0570000e+00],
       [6.9222440e+06, 1.4510000e+00],
       [8.3956600e+06, 1.0290000e+00],
       [9.5796410e+06, 1.3320000e+00],
       [1.0666592e+07, 1.9910000e+00],
       [1.0797460e+07, 1.0400000e+00],
       [1.0854555e+07, 1.0460000e+00],
       [1.0875245e+07, 1.4110000e+00],
       [1.0984090e+07, 1.0730000e+00],
       [1.1138155e+07, 1.0250000e+00],
       [1.1304958e+07, 1.0460000e+00],
       [1.1403044e+07, 1.1030000e+00],
       [1.1493732e+07, 1.0910000e+00],
       [1.1904151e+07, 1.0560000e+00]])

In [14]:
stars[:,1].argsort()

array([53, 59, 12, 56, 27, 50,  1, 25, 24, 55, 17, 36, 14, 60, 22, 11,  6,
       63, 52, 13, 43, 16, 64, 39, 32, 26, 10, 51,  7, 38, 46,  2, 29,  8,
       58, 31, 18,  9, 61, 65, 62, 15, 23,  0, 45, 41, 49, 34,  3, 47, 57,
       40, 20, 30, 33, 42, 54,  5,  4, 37, 48, 44, 21, 35, 19, 28])

In [15]:
stars[stars[:,1].argsort(), :]

array([[1.1853255e+07, 4.5000000e-01],
       [1.2066335e+07, 4.8000000e-01],
       [4.1398160e+06, 4.8000000e-01],
       [1.1923270e+07, 4.9000000e-01],
       [1.0662202e+07, 5.2700000e-01],
       [1.1754553e+07, 5.4000000e-01],
       [3.1141670e+06, 6.7700000e-01],
       [1.0583066e+07, 6.9300000e-01],
       [1.0526549e+07, 6.9600000e-01],
       [1.1918099e+07, 7.2700000e-01],
       [5.4566510e+06, 7.3400000e-01],
       [1.0910878e+07, 7.4200000e-01],
       [4.4761230e+06, 7.5100000e-01],
       [1.2070811e+07, 7.5200000e-01],
       [1.0187017e+07, 7.5500000e-01],
       [4.0491310e+06, 7.6100000e-01],
       [3.4532140e+06, 7.7000000e-01],
       [1.2404086e+07, 7.7500000e-01],
       [1.1818800e+07, 7.8100000e-01],
       [4.2751910e+06, 7.8100000e-01],
       [1.1391957e+07, 7.8200000e-01],
       [5.3586240e+06, 7.8800000e-01],
       [1.2470844e+07, 7.8800000e-01],
       [1.1018648e+07, 7.9600000e-01],
       [1.0848459e+07, 8.0300000e-01],
       [1.0601284e+07, 8.

In [16]:
def query(file_name):
    stars = np.loadtxt(file_name, delimiter=',', usecols=(0,2))
    big_stars = stars[stars[:, 1] > 1.0,:]
    return big_stars[big_stars[:,1].argsort(), :]

In [17]:
query('stars.csv')

array([[1.1138155e+07, 1.0250000e+00],
       [8.3956600e+06, 1.0290000e+00],
       [1.0797460e+07, 1.0400000e+00],
       [1.0854555e+07, 1.0460000e+00],
       [1.1304958e+07, 1.0460000e+00],
       [1.1904151e+07, 1.0560000e+00],
       [3.3518880e+06, 1.0570000e+00],
       [3.3429700e+06, 1.0640000e+00],
       [1.0984090e+07, 1.0730000e+00],
       [1.1493732e+07, 1.0910000e+00],
       [1.1403044e+07, 1.1030000e+00],
       [9.5796410e+06, 1.3320000e+00],
       [1.0875245e+07, 1.4110000e+00],
       [6.9222440e+06, 1.4510000e+00],
       [1.0666592e+07, 1.9910000e+00]])

In [68]:
def query(stars_file, planets_file):
    stars = np.loadtxt(stars_file, delimiter=',', usecols=(0,2))
    stars = stars[stars[:, 1] > 1.0,:]
    planets = np.loadtxt(planets_file, delimiter=',', usecols=(0,5))

    result = []
    for star in stars:
        kepler_id = star[0]
        star_radius = star[1]
        star_planets = planets[planets[:,0]==kepler_id ,:]
        planet_ratio = star_planets[:,1] / star_radius

        result = np.concatenate((result, planet_ratio))

    result = np.sort(result)
    return np.reshape(result, (-1,1))

In [69]:
query('stars.csv', 'planets.csv')

array([ 0.48798799,  0.8260447 ,  0.96209913,  1.1556384 ,  1.30403969,
        1.37310606,  1.41141141,  2.28377065,  2.46246246,  2.50728863,
        2.59082218,  2.98076923,  2.98076923,  3.29887218,  3.40225564,
        4.04351768,  5.47801147,  8.2320442 ,  9.21475875, 10.22053756,
       11.5902439 , 58.87259395])